# Generated by Django 3.2.25 on 2025-04-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeunlock',
            name='icon',
            field=models.CharField(default='💰', max_length=10),
        ),
    ]
