# Generated by Django 5.2 on 2025-05-05 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='budget',
        ),
        migrations.AddField(
            model_name='income',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='main_app.calendar'),
            preserve_default=False,
        ),
    ]
