# Generated by Django 3.2.25 on 2025-04-24 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_alter_transaction_options_transaction_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeunlock',
            name='icon',
            field=models.CharField(default='💰', max_length=10),
        ),
        migrations.AddField(
            model_name='modeunlock',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modeunlock',
            name='streak_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ModeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_name', models.CharField(max_length=50)),
                ('status_change', models.CharField(choices=[('unlocked', 'Mode Unlocked'), ('locked', 'Mode Locked'), ('progress', 'Progress Updated')], max_length=50)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
