# Generated by Django 5.2 on 2025-04-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_category_transaction_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('utilities', 'Utilities'), ('gas', 'Gas'), ('mortgage', 'Mortgage'), ('rent', 'Rent'), ('entertainment', 'Entertainment'), ('transportation', 'Transportation'), ('dining_out', 'Dining Out'), ('groceries', 'Groceries'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#00ff00', max_length=7),
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
