# Generated by Django 5.2 on 2025-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budgeting_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=10),
        ),
    ]
