# Generated by Django 5.2 on 2025-04-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_budget_budgeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='budgeting_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUALLY', 'Annually'), ('WEEKLY', 'Weekly')], default='MONTHLY', max_length=10),
        ),
    ]
