# Generated by Django 5.2 on 2025-04-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type'], 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fa-bolt', 'Utilities ⚡'), ('fa-gas-pump', 'Gas ⛽'), ('fa-home', 'Mortgage 🏠'), ('fa-building', 'Rent 🏢'), ('fa-film', 'Entertainment 🎬'), ('fa-bus', 'Transportation 🚌'), ('fa-utensils', 'Dining Out 🍽️'), ('fa-shopping-cart', 'Groceries 🛒'), ('fa-question', 'Other ❓')], default='fa-question', max_length=32),
        ),
    ]
