# Generated by Django 5.2 on 2025-04-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_category_options_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
