# Generated by Django 5.2 on 2025-04-29 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20250424_0218'),
        ('main_app', '0007_budgetitem'),
        ('main_app', '0007_category_custom_name'),
    ]

    operations = [
    ]
