# Generated by Django 3.2.25 on 2025-04-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_update_mode_icons'),
        ('main_app', '0009_budget_category'),
    ]

    operations = [
    ]
