# Generated by Django 3.2.25 on 2025-04-30 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0012_categoryspendinglimit_freedomexpense_freedomfundplan_savingscontribution_savingsgoal_stabilityratiot'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssentialBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('housing', 'Housing (Mortgage/Rent)'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('health', 'Healthcare'), ('debt', 'Minimum Debt Payments'), ('insurance', 'Insurance'), ('other', 'Other Essential')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('scheduled', 'Scheduled'), ('deferred', 'Deferred')], default='unpaid', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
