# Generated by Django 5.2 on 2025-04-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_categoryspendinglimit_freedomexpense_freedomfundplan_savingscontribution_savingsgoal_stabilityratiot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('utilities', 'Utilities'), ('gas', 'Gas'), ('mortgage', 'Mortgage'), ('rent', 'Rent'), ('entertainment', 'Entertainment'), ('transportation', 'Transportation'), ('dining_out', 'Dining Out'), ('groceries', 'Groceries'), ('savings', 'Savings'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fa-bolt', 'Utilities ⚡'), ('fa-gas-pump', 'Gas ⛽'), ('fa-home', 'Mortgage 🏠'), ('fa-building', 'Rent 🏢'), ('fa-film', 'Entertainment 🎬'), ('fa-bus', 'Transportation 🚌'), ('fa-utensils', 'Dining Out 🍽️'), ('fa-shopping-cart', 'Groceries 🛒'), ('fa-piggy-bank', 'Savings 🐷'), ('fa-question', 'Other ❓')], default='fa-question', max_length=32),
        ),
    ]
