# Generated by Django 5.2 on 2025-05-02 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_category_category_type_alter_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='allocation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investments', 'Investments'), ('bonus', 'Bonus'), ('utilities', 'Utilities'), ('gas', 'Gas'), ('mortgage', 'Mortgage'), ('rent', 'Rent'), ('entertainment', 'Entertainment'), ('transportation', 'Transportation'), ('dining_out', 'Dining Out'), ('groceries', 'Groceries'), ('savings', 'Savings'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='EssentialBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('housing', 'Housing (Mortgage/Rent)'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('health', 'Healthcare'), ('debt', 'Minimum Debt Payments'), ('insurance', 'Insurance'), ('other', 'Other Essential')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('scheduled', 'Scheduled'), ('deferred', 'Deferred')], default='unpaid', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
